# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
# Be sure to edit files/docker-compose.yml for your application
- name: copy Docker Compose files
  copy:
    src: files/docker-compose.yml
    dest: /opt/ansible/podman_traefik/

- name: Copy Traefik Configuration
  copy:
    src: files/traefik.yaml
    dest: /opt/ansible/podman_traefik/