# Deploy <template> Pod
# https://docs.ansible.com/ansible/latest/collections/containers/podman/index.html

- name: Deploy <template> pod
  containers.podman.podman_container:
    name: <template>
    image: docker.io/<template>/latest
    env: " "
    ports:
      - "9443:9443"
    privileged: true
    volume:
       - "/tmp/example:/tmp/example"
    state: started