---
# tasks file for podman_install_<template>

# Installs and enables Podman
- include_tasks: EnablePodman.yaml
# Insert tasks here that need to occur before deploying the container

# Deploy Container
# Depending on deployment choice, this will be either DeployContainer.yml or ComposeContainer.yml
# - include_tasks: DeployContainer.yml
- include_tasks: ComposeContainer.yaml


# Insert tasks here that need to occur after deploying the container



