---
# tasks file for ubuntu_install_portainer

## Installs Ubuntu Packages necessary for portainer packages listed in vars/main.yml
# https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Install Ubuntu Packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600


- name: Enable podman.socket
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true

