---
# tasks file for ubuntu_install_portainer

## Installs Ubuntu Packages necessary for portainer packages listed in vars/main.yml
# https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Install Ubuntu Packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html
- name: Enable podman.socket
  ansible.builtin.systemd:
    name: podman.socket
    enabled: true

- name: Pull an image
  containers.podman.podman_image:
    name: portainer/portainer-ce

# Echo admin password to local file so we can pass it to portainer on first start
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/command_module.html
# NOT SAFE FOR PRODUCTION
- name: Echo admin password to local file
  ansible.builtin.command:
    cmd: echo -n " {{ admin_password }} " > /tmp/portainer_password
    args:
      creates: /tmp/portainer_password

# Deploy Portainer Pod
# https://docs.ansible.com/ansible/latest/collections/containers/podman/index.html
- name: Deploy Portainer-CE pod
  containers.podman.podman_container:
    name: portainer-ce
    image: docker.io/portainer/portainer-ce
    command: "--admin-password-file /root/portainer_admin_password"
    ports:
      - "9443:9443"
    privileged: true
    volume:
       - "/run/podman/podman.sock:/var/run/docker.sock:Z"
       - "/tmp/portainer_password:/tmp/portainer_password"
    # volume: portainer_data:/data (need to crate portainer_data first)
    state: started