# Echo admin password to local file so we can pass it to portainer on first start
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html#ansible-collections-ansible-builtin-shell-module
# NOT SAFE FOR PRODUCTION
- name: Copy admin password to local file
  ansible.builtin.copy:
    content: "{{ admin_password }}"
    dest: /opt/ansible/podman_portainer/portainer_password
    mode: 0600




#- name: Echo admin password to local file
#  ansible.builtin.shell:
#    cmd: echo -n "{{ admin_password }}" > /tmp/portainer_password
#    creates: /tmp/portainer_password