---
# tasks file for podman_install_portainer

# Installs and enables Podman
- include_tasks: EnablePodman.yml

# Insert tasks here that need to occur before deploying the container
- include_tasks: CreatePasswordfile.yml

# Deploy Container
# Depending on deployment choice, this will be either DeployContainer.yml or ComposeContainer.yml
# - include_tasks: DeployContainer.yml
- include_tasks: ComposeContainer.yml

# Insert tasks here that need to occur after deploying the container


