---
## Installs Ubuntu Packages
## packages are listed in host_vars as "host_packages"
- hosts: ubuntu
  become: true
  gather_facts: False
  vars:
    packages: "{{ host_packages }}"
  roles:
    - ubuntu_install_package