
# Configuration  for Traefik v2.
# https://doc.traefik.io/traefik/getting-started/install-traefik/

global:
  checkNewVersion: true
  sendAnonymousUsage: false
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https
##todo add in redirections so everything goes to 443
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
log:
  level: DEBUG
  filePath: logs/traefik.log
  format: common
accessLog:
  filePath: /logs/accesslog.txt
  format: common

# NOT SECURE FOR PRODUCTION
api:
  insecure: true
  dashboard: true
ping:
  entryPoint: traefik
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    network: "proxy"
  file:
    filename: ""