
# Configuration  for Traefik v2.
# https://doc.traefik.io/traefik/getting-started/install-traefik/

global:
  checkNewVersion: true
  sendAnonymousUsage: false
entryPoints:
  http:
    address: ":80"
##todo add in redirections so everything goes to 443
  https:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
log:
  level: ERROR
  filePath: log/traefik.log
  format: common

accessLog:
  filePath: /logs/accesslog.txt
  format: common

# NOT SECURE FOR PRODUCTION
api:
  insecure: true
  dashboard: false
ping:
  entryPoint: traefik
providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    defaultRule: Host(`{{ normalize .Name }}.lab.travellingtechie.com`)
    exposedByDefault: true